// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eplxmfdbntfltvqbdzok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwbHhtZmRibnRmbHR2cWJkem9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzEyNjMsImV4cCI6MjA2NjYwNzI2M30.dcMK_SM9deQHKl53daBLfZ4DsSwtkCXPxe0MYlJ__lk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);